### PR TITLE
Fixes because typo and rating @<player> syntax

### LINKED ISSUE #21: @chesster rating @<player> fails

### PR DESCRIPTION
**Pull request by aweidner**
This fixes #21 and #32.  I factored out the code to pull a player id so we can generate commands that take players as an argument and it should work with:

player
@player
playerMixedCase
aj;sldfkajs;dlfkj (garbage)
<blank>

### CODE REVIEW

File: chesster.js [hunk 1]
```diff
@@ -7,6 +7,7 @@ var fuzzy = require('./fuzzy_match.js');
 var spreadsheets = require('./spreadsheets.js');
 var http = require('http');
 var moment = require('moment');
+var players = require("./player.js");
```
Comment (endrawes0) [inline chesster.js]: Yes. More of this please 👍 

We should continue to make minor improvements like this.

File: chesster.js [hunk 2]
```diff
@@ -300,14 +301,13 @@ function sayCaptains(self, convo, callback){
 /* rating */
 
 controller.hears([
-	'rating'
+    players.appendPlayerRegex("rating", true)
```
Comment (endrawes0) [inline chesster.js]: with this change I think we can remove the error handling below.

it will no longer match if there is no player

Comment (endrawes0) [inline chesster.js]: I cant put a comment on the line so I'll note it here: error on line 320 can be removed.

File: chesster.js [hunk 3]
```diff
@@ -1604,7 +1581,7 @@ function validate_game_details(details, options){
 
 function gamelink_reply_invalid(bot, message, reason){
     bot.reply(message, "I am sorry, <@" + message.user + ">,  "
-                     + "the link you posted is *not valid* becuase "
+                     + "the link you posted is *not valid* because "
```
Comment (endrawes0) [inline chesster.js]: thank you.

File: player.js [hunk 4]
```diff
@@ -0,0 +1,37 @@
+module.exports.appendPlayerRegex = function(command, optional) {
+    var playerRegex = command + "(?: @?([^\\s]+))";
```
Comment (endrawes0) [inline player.js]: can you put a comment in that explains the regex? thank you :)

File: player.js [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+
+    if (optional) {
+        return new RegExp(playerRegex + "?");
+    }
+
+    return new RegExp(playerRegex);
+};
+
+module.exports.getSlackUser = function(users, message) {
```
Comment (endrawes0) [inline player.js]: doesnt need to happen now, but probably lichess user info could be added here... 

OR maybe we move all the lichess stuff into its own js file. in any case, more refactoring and better code organization.

**Comment by endrawes0** [comment]
Hey Ghost. 

I made a few comments/requests.

Please take a look. 

Thanks.
Andrew
